name: ChatSystem
author: xGamerTim
version: ${project.version}
api-version: 1.18
loadbefore:
  - Essentials
  - EssentialsX
  - LuckPerms
  - CloudNet-Bridge

main: net.evergreenmc.chatsystem.ChatSystem

commands:
  msg:
    aliases: [m,tell,tellraw,whisper]