name: ChatSystem
author: xGamerTim
version: v1.0
api-version: 1.18
depend:
  - CloudNet-Bridge
  - LuckPerms
loadbefore:
  - Essentials
  - EssentialsX

main: net.evergreenmc.chatsystem.ChatSystem

commands:
  msg: